# --- !Ups

CREATE TABLE user (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(128) UNIQUE NOT NULL,
	password TEXT NOT NULL,
	fname VARCHAR(32) NOT NULL,
	lname VARCHAR(32) NOT NULL,
	admin BOOLEAN NOT NULL
);

# --- !Downs

DROP TABLE user;

